### ISSUE TITLE
error when generating

### ISSUE THREAD

**Issue by wada-s** [dhgrs/chainer-Fast-WaveNet#4]
Hi !
When I generated with "use_logisitic = False" setting, I got an error like the following.

`Traceback (most recent call last):
  File "generate.py", line 117, in <module>
    p=chainer.functions.softmax(out).array[0, :, 0, 0])
  File "/work/wada/chainer-ClariNet/virtual3.5/lib/python3.5/site-packages/cupy/random/sample.py", line 192, in choice
    return rs.choice(a, size, replace, p)
  File "/work/wada/chainer-ClariNet/virtual3.5/lib/python3.5/site-packages/cupy/random/generator.py", line 423, in choice
    raise NotImplementedError
NotImplementedError`

I think the argument of decoder.xp.random.choice is a problem (size = None).
How can I deal with it?

**Comment by dhgrs** [comment]
Hi,

I had same error with some cupy versions. And sorry for forgetting working version. Fisrt, can you try cupy 4.0.0b3?

FYI: If you want to try mu law quantized WaveNet with Chainer, you can also use [official example](https://github.com/chainer/chainer/tree/master/examples/wavenet). It was based on this repository. And I tested to work generating on CPU/GPU with latest Chainer and Cupy.

**Comment by wada-s** [comment]
Thank you for your prompt reply.
I had tried some cupy versions but I had same error.

The script was run when changing the script with reference to official example as follows
`        value = decoder.xp.random.choice(
            params.quantize,size=1,
            p=chainer.functions.softmax(out).array[0, :, 0, 0])[0]`

**Comment by dhgrs** [comment]
I think that Cupy should perform as same as Numpy, so it's maybe Cupy's bug. If you need, please create issue on Cupy repository.

And thank you for fixing. Could you send a PR if it works with latest Chainer/Cupy?

**Comment by wada-s** [comment]
I see.
I checked that the script works with chainer (5.0.0b4).

**Comment by dhgrs** [comment]
I want you to be a contributor so if you have a time, please send a PR!
