### ISSUE TITLE
Gated activation units

### ISSUE THREAD

**Issue by wada-s** [dhgrs/chainer-Fast-WaveNet#5]
Hi !
I have a doubt in Gated activation units in modules.py.

What do the following implementations mean?
`tanh_z, sig_z = F.split_axis(h, 2, axis=1)`
It is not the same as the WaveNet paper, is it?

**Comment by dhgrs** [comment]
Gated Linear Unit is an activation function that applies `f(x) = tanh(x_a) * sigmoid(x_b)` where `x_a, x_b = split(x)`. It needs split function.

**Comment by wada-s** [comment]
Thank you for your reply.
I noticed my misunderstanding point.
